name: CI
on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler: [
          {os: ubuntu-24.04, cpp: clang++, c: clang},
          {os: windows-latest, cpp: cl, c: cl},
        ]
    runs-on: ${{ matrix.compiler.os }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }}
        -DCMAKE_C_COMPILER=${{ matrix.compiler.c }}
        ${{ format('-D{0}={1}', matrix.compiler.os == 'windows-latest' && 'CMAKE_CONFIGURATION_TYPES' || 'CMAKE_BUILD_TYPE', matrix.build_type) }}
        ${{ matrix.compiler.os != 'windows-latest' && '-G Ninja' || ''}}
        -DCMAKE_UNITY_BUILD=ON
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
    - name: Generate Changelog
      run: git show -s --format='%b' > ${{ github.workspace }}-CHANGELOG.txt
      if: startsWith(github.ref, 'refs/tags/')
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release'
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        files: |
          ${{ steps.strings.outputs.build-output-dir }}/trimja
          ${{ steps.strings.outputs.build-output-dir }}/trimja.exe
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '17'
        check-path: 'src'
