name: CI
on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        environment: [
          # Linux (Clang) and MacOS must use the oldest GitHub Action runner
          # since we want to compile against the oldest libc version
          # possible.  This means that all binaries created will be compatible
          # with all GitHub Action runners. For Linux (GCC) with choose the
          # oldest version that supports everything we have on the other
          # platforms to maximise compiler compatibility.
          {name: Linux (clang), image: ubuntu-22.04, cpp: clang++-13, c: clang-13, generator: Ninja, clang-tidy: true, package: true},
          {name: Linux (gcc), image: ubuntu-22.04, cpp: g++-12, c: gcc-12, generator: Ninja, package: false},
          {name: MacOS, image: macos-13, cpp: clang++, c: clang, generator: Ninja, package: true},
          {name: Windows, image: windows-latest, cpp: cl, c: cl, package: true},
          # Compile on the latest clang to get the latest clang-tidy
          {name: Linux (clang-latest), image: ubuntu-latest, cpp: clang++, c: clang, generator: Ninja, clang-tidy: true, package: false},
        ]
        build_type: [Debug, Release]
    name: ${{ matrix.environment.name }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.environment.image }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Configure CMake
      run: >
        cmake -B output
        -DCMAKE_CXX_COMPILER=${{ matrix.environment.cpp }}
        -DCMAKE_C_COMPILER=${{ matrix.environment.c }}
        ${{ format('-D{0}={1}', matrix.environment.name == 'Windows' && 'CMAKE_CONFIGURATION_TYPES' || 'CMAKE_BUILD_TYPE', matrix.build_type) }}
        ${{ matrix.environment.generator != '' && format('-G {0}', matrix.environment.generator) || ''}}
        ${{ matrix.environment.clang-tidy && '-DENABLE_CLANG_TIDY=ON' || ''}}
    - uses: elliotgoodrich/trimja-action@v1
      # Skip Windows (which doesn't yet use Ninja) and releases
      # TODO: Figure out why trimja is failing on CI
      #if: matrix.environment.name != 'Windows' && !startsWith(github.ref, 'refs/tags/')
      if: false
      with:
        path: output/build.ninja
        build-configuration: ${{ matrix.build_type }}
        # CTest does not have the right dependencies so we always build everything, we
        # won't gain any time, but will verify that trimja can at least handle a Ninja
        # file generated by CMake.
        affected: |
          test
          trimja
    - name: Build
      run: cmake --build output --config ${{ matrix.build_type }}
    - name: Test
      run: ctest --test-dir output --build-config ${{ matrix.build_type }} --output-on-failure
    - name: Install
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package
      run: cmake --build output --config ${{ matrix.build_type }} --target package
    - name: Generate Changelog
      run: git show -s --format='%b' > output/CHANGELOG.txt
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package
      with:
        body_path: output/CHANGELOG.txt
        files: |
          output/trimja-*-Linux.tar.gz
          output/trimja-*-Darwin.tar.gz
          output/trimja-*-win64.exe
          output/trimja-*.zip
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '17'
        check-path: 'src'
