name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
        build_type: [Debug, Release]
        compiler: [{cpp: clang++, c: clang}, {cpp: cl, c: cl}]
        exclude:
          - os: ubuntu-24.04
            compiler: {cpp: cl, c: cl}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }}
        -DCMAKE_C_COMPILER=${{ matrix.compiler.c }}
        ${{ format('-D{0}={1}', matrix.os == 'windows-latest' && 'CMAKE_CONFIGURATION_TYPES' || 'CMAKE_BUILD_TYPE', matrix.build_type) }}
        ${{ matrix.os != 'windows-latest' && '-G Ninja' || ''}}
        -DCMAKE_UNITY_BUILD=ON
        -DCMAKE_C_COMPILER_FORCED=TRUE
        -DCMAKE_CXX_COMPILER_FORCED=TRUE
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '17'
        check-path: 'src'
