name: CI
on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        environment: [
          # Linux (Clang) and MacOS must use the oldest GitHub Action runner
          # since we want to compile against the oldest libc version
          # possible.  This means that all binaries created will be compatible
          # with all GitHub Action runners. For Linux (GCC) with choose the
          # oldest version that supports everything we have on the other
          # platforms to maximise compiler compatibility.
          {name: Linux (clang), image: ubuntu-22.04, cpp: clang++-13, c: clang-13, generator: Ninja, clang-tidy: true, package: true},
          {name: Linux (gcc), image: ubuntu-22.04, cpp: g++-12, c: gcc-12, generator: Ninja, package: false},
          {name: MacOS, image: macos-14, cpp: clang++, c: clang, generator: Ninja, package: true},
          {name: Windows, image: windows-latest, cpp: cl, c: cl, package: true},
          # Compile on the latest clang to get the latest clang-tidy
          {name: Linux (clang-latest), image: ubuntu-latest, cpp: clang++, c: clang, generator: Ninja, clang-tidy: true, package: false},
        ]
        build_type: [Debug, Release]
    name: ${{ matrix.environment.name }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.environment.image }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
    - name: Configure CMake
      run: >
        cmake -B output
        -DCMAKE_CXX_COMPILER=${{ matrix.environment.cpp }}
        -DCMAKE_C_COMPILER=${{ matrix.environment.c }}
        ${{ format('-D{0}={1}', matrix.environment.name == 'Windows' && 'CMAKE_CONFIGURATION_TYPES' || 'CMAKE_BUILD_TYPE', matrix.build_type) }}
        ${{ matrix.environment.generator != '' && format('-G {0}', matrix.environment.generator) || ''}}
        ${{ matrix.environment.clang-tidy && '-DENABLE_CLANG_TIDY=ON' || ''}}
    - uses: elliotgoodrich/trimja-action@v2
      # Skip Windows (which doesn't yet use Ninja) and releases
      if: matrix.environment.name != 'Windows' && !startsWith(github.ref, 'refs/tags/')
      with:
        version: 1.3.1
        path: output/build.ninja
        build-configuration: ${{ matrix.environment.name }} ${{ matrix.build_type }}
        target-default: true
        targets: |
          run_test_with_dependencies
        explain: true
    - name: Build
      run: cmake --build output --config ${{ matrix.build_type }}
    - name: Test
      run: cmake --build output --target run_test_with_dependencies --config ${{ matrix.build_type }}
    - name: Install NSIS
      # windows-latest no longer ships NSIS, but we need it to build the .exe installer
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package && matrix.environment.name == 'Windows'
      run: choco install nsis -y --no-progress
    - name: Install
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package
      run: cmake --build output --config ${{ matrix.build_type }} --target package
    - name: Generate Changelog
      run: git show -s --format='%b' > output/CHANGELOG.txt
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package
    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' && matrix.environment.package
      with:
        body_path: output/CHANGELOG.txt
        files: |
          output/trimja-*-Linux.tar.gz
          output/trimja-*-Darwin.tar.gz
          output/trimja-*-win64.exe
          output/trimja-*.zip
  format:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: Run clang-format
      run: >
        git ls-files -z
        'src/*.c' 'src/*.h' 'src/*.cpp' 'src/*.hpp'
        'src/*.cc' 'src/*.hh' 'src/*.cxx' 'src/*.hxx'
        | xargs -0 clang-format --dry-run --Werror
